version: '2.0'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch-one
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - cluster.name=docker-cluster
      - node.name=node-one
      - node.master=true
      - network.publish_host=192.168.43.78
      - network.bind_host=0.0.0.0
      - discovery.zen.ping.unicast.hosts=192.168.43.78,192.168.43.184
      - discovery.zen.minimum_master_nodes=1
    volumes:
      - /var/db/elasticsearch-6-2-4/data:/usr/share/elasticsearch/data
      #- ./elasticsearch-one-conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
