version: '2.0'
services:
  elasticsearch-two:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch-two
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - cluster.name=docker-cluster
      - node.name=node_two
      - node.master=false
      - network.publish_host=192.168.43.184
      - network.bind_host=0.0.0.0
      - discovery.zen.ping.unicast.hosts=192.168.43.78,192.168.43.184
      - discovery.zen.ping_timeout=3s
      - discovery.zen.minimum_master_nodes=1 
    volumes:
      - /var/db/elasticsearch5-6-3/data:/usr/share/elasticsearch/data
      #- ./elasticsearch-two-conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
